### ISSUE TITLE
I could not contact you anymore

### ISSUE THREAD

**Issue by khanhduytran0** [pedrosouzabrasil/minecraft#1]
Hi. I'm unable to send any more emails to you, it always queue. I just hoping this account won't be deleted or disabled. There's no more ways to contact you. Bye. Out of touch..

**Comment by khanhduytran0** [comment]
Please feel better.

Best regards,

**Comment by pedrosouzabrasil** [comment]
i send you gmail.

Em sex, 4 de dez de 2020 07:18, Duy Tran Khanh <notifications@github.com>
escreveu:

**Comment by khanhduytran0** [comment]
I always get "Queued emails".
Don't be confused early...
@.LegacyGamerHD replied it was a test only.
![_20201204_115529](https://user-images.githubusercontent.com/40482367/101161205-d13c0a80-3662-11eb-9226-3f4ca4a71cbc.jpg)

If other problems, I will not bother you anymore.

**Comment by pedrosouzabrasil** [comment]
Ok no problem..keep amazing work..

Em sex, 4 de dez de 2020 09:03, Duy Tran Khanh <notifications@github.com>
escreveu:

**Comment by pedrosouzabrasil** [comment]
Its life problems for the most...no worry i will be better soon

Em sex, 4 de dez de 2020 10:11, Pedro Souza <pedrosouza1996rj@gmail.com>
escreveu:

**Comment by pedrosouzabrasil** [comment]
good afternoon...thanks for kind message!i will comeback in a later moment
to your discord...i need a time to think about my personal life and other
things...you really worry about me ...i feel so glad about this!have a
blessed day


Em sex, 4 de dez de 2020 10:36, Pedro Souza <pedrosouza1996rj@gmail.com>
escreveu:

**Comment by khanhduytran0** [comment]
Good morning

Ok...

**Comment by pedrosouzabrasil** [comment]
Good night!

Em sex, 4 de dez de 2020 10:51, Duy Tran Khanh <notifications@github.com>
escreveu:
